# config/routes.yaml
login:
    path: /login
    controller: App\Controller\LoginController::login

Asistencia_route:
    path: /asistencia
    # Aquí especifica el controlador y método al que debe dirigirse esta ruta
    controller: App\Controller\Admin\AsistenciaController::class

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

